apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: the-office-chat-bot
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: the-office-chat-bot
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
